---
number_format:
  title: Tiketin Numerointimalli
  content: >
    Tätä asetusta käytetään tikettien numeroiden luomisessa. Käytä ruutumerkkiä (`#`) mihin numerot tulee laittaa. Mitä tahansa muuta tekstiä numeromuodossa tulee välttää. <span class="doc-desc-title">Ohjeotsikoissa</span> voidaan määrittää muokattuja numeromuotoja. <br/><br/> Esimerkiksi, 6-numeroinen muoto, käytä <code>######</code>.
sequence_id:
  title: Tikettinumerointijakso
  content: >
    Määritä jakso mistä aloitetaan uudet tikettinumerot. Järjestelmässä on kasvava järjestys ja satunnainen järjestys oletuksena. Voit luoda niin monia järjestyksiä kuin haluat. Käytä Ohjeotsikoihin useita järjestyksiä <span class="doc-desc-title">Tikettinumeron muotojen</span> asetuksissa.
default_ticket_status:
  title: Uusien Tikettien Oletustila
  content: >
    Valitse oletustila uusille tiketeille. Tämä voidaan määrittää haluttaessa jokaiselle ohjeotsikolle. Tämä voidaan myös ohittaa tikettisuodattimessa.
  links:
    - 
      title: Hallinnoi Tikettien Tilaa
      href: /scp/lists.php?type=ticket-status
default_sla:
  title: Oletus SLA (Palvelutasosopimus)
  content: >
    Valitse oletus Palvelutaso, jonka perusteella määritetään kuinka kauan tiketti voi olla avoin ennen kuin se merkitään myöhässä olevaksi.
  links:
    - 
      title: Luo lisää Palvelutasosopimuksia
      href: /scp/slas.php
default_priority:
  title: Oletus Prioriteetti
  content: >
    Valitse oletus <span class="doc-desc-title">prioriteetti</span> tiketeille, joille ei ole automaattisesti määritetty prioriteettia. <br/><br/> Prioriteetti voidaan määrittää Ohjeotsikon, osaston tai tikettisuodattimen asetuksissa.
maximum_open_tickets:
  title: Maksimi määrä avoimia tikettejä
  content: >
    Syötä maksimi <em>määrä</em> tikettejä, joita Asiakkaalla voi olla <strong>avoinna</strong> tukisivustossa. <br><br> Syötä <span class="doc-desc-opt">0 </span> jos haluat poistaa tämän rajoituksen.
email_ticket_priority:
  title: Sähköpostitikettien Prioriteetti
  content: >
    Käytä lähettäjän sähköpostipalvelun sähköpostin prioriteettiä
show_related_tickets:
  title: Näytä Liittyvät Tiketit
  content: >
    Näytä kaikki liittyvät tiketit asiakkaan kirjautuessa - Muutoin näkymä rajoitetaan yksittäiseen tikettiin
human_verification:
  title: Ihmisen todentaminen
  content: >
    Aktivoi CAPTCHA Asiakasportaalissa vahvistaaksesi että luotu tiketti on ihmisen tekemä. <br><br> Vaatii GDLib kirjaston
claim_tickets:
  title: Lunasta tiketit itsellesi vastauksen yhteydessä
  content: >
    Aktivoi tämä jotta kohdistamattomat tiketit kohdistetaan automaattisesti Käsittelijälle joka vastaa niihin. <br><br> Uudelleen avatut tiketit kohdistetaan aina viimeisimmälle vastaajalle.
assigned_tickets:
  title: Osoitetut tiketit
  content: >
    Aktivoi tämä ominaisuus jotta kohdistetut tiketit poistetaan <span class="doc-desc-title">Avoimien tikettien listasta</span>.
answered_tickets:
  title: Vastatut tiketit
  content: >
    Aktivoi tämä jotta vastatut tiketit näytetään <span class="doc-desc-title">Vastattujen tikettien listassa</span>. Muutoin, nämä sisältyvät <span class="doc-desc-title">Avoimien tikettien listaan</span>.
ticket_attachment_settings:
  title: Tikettien Liitteet
  content: >
    Määritä asetukset liitetiedostoille <span class="doc-desc-title">Aiheen tiedot</span> kentässä. Nämä asetukset ovat käytössä kaikissa uusissa tiketeissä ja viesteissä riippumatta kanavasta (Verkkosivusto, Sähköposti, API, jne.).
