---
number_format:
  title: Tiketin Numerointimalli
  content: >
    Tätä asetusta käytetään tikettien numeroiden luomisessa. Käytä ruutumerkkiä (`#`) mihin numerot tulee laittaa. Mitä tahansa muuta tekstiä numeromuodossa tulee välttää. <br/><br/> Esimerkiksi, 6-numeroinen muoto, käytä <code>######</code>.
sequence_id:
  title: Tikettinumerointijärjestys
  content: >
    Choose a sequence from which to derive new task numbers. The system has a incrementing sequence and a random sequence by default. You may create as many sequences as you wish.
default_sla:
  title: Oletus SLA (Palvelutasosopimus)
  content: >
    Valitse oletus Palvelutaso, jonka perusteella määritetään kuinka kauan tiketti voi olla avoin ennen kuin se merkitään myöhässä olevaksi.
  links:
    - 
      title: Luo lisää Palvelutasosopimuksia
      href: /scp/slas.php
default_priority:
  title: Oletus Prioriteetti
  content: >
    Valitse <span class="doc-desc-title">oletusprioriteetti</span> tehtäville joiden prioriteettia ei ole asetettu.
task_attachment_settings:
  title: Tikettien Liitteet
  content: >
    Määritä asetukset liitetiedostoille <span class="doc-desc-title">Aiheen tiedot</span> kentässä. Nämä asetukset ovat käytössä kaikissa uusissa tiketeissä ja viesteissä riippumatta kanavasta (verkkosivusto, sähköposti, api, jne.).
page_title:
  title: Ilmoitukset ja Muistutukset
  content: >
    Ilmoitukset ja muistutukset ovat automaattisia sähköpostiviestejä jotka lähetetään Käsittelijöille, kun tiketin tapahtumat käynnistyvät.
task_alert:
  title: New Task Alert
  content: >
    <p>Ilmoitus lähetetään Käsittelijöille, kun uusi tiketti luodaan.</p><p class="info-banner"> <i class="icon-info-sign"></i> Ilmoitusta ei lähetetä, jos tiketti automaattisesti siirretään Tikettisuodattimen tai Ohjeotsikon perusteella.</p>
  links:
    - 
      title: Default New Task Alert Template
      href: /scp/templates.php?default_for=task.alert
activity_alert:
  title: New Activity Alert
  content: >
    Alert sent out to Agents when a new message is appended to an existing task.
  links:
    - 
      title: Default New Activity Alert Template
      href: /scp/templates.php?default_for=task.activity.alert
assignment_alert:
  title: Task Assignment Alert
  content: >
    Alert sent out to Agents on task assignment.
  links:
    - 
      title: Default Task Assignment Alert Template
      href: /scp/templates.php?default_for=task.assignment.alert
transfer_alert:
  title: Task Transfer Alert
  content: >
    Alert sent out to Agents on task transfer between Departments.
  links:
    - 
      title: Default Task Transfer Alert Template
      href: /scp/templates.php?default_for=task.transfer.alert
overdue_alert:
  title: Overdue Task Alert
  content: >
    Alert sent out to Agents when a task becomes overdue based on SLA or Due Date.
  links:
    - 
      title: Default Stale Task Alert Template
      href: /scp/templates.php?default_for=task.overdue.alert
    - 
      title: Hallinnoi Palvelutasoja
      href: /scp/slas.php
